name: Build Release
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Using a more modern stable Node version

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install & Build Project
        run: |
          # 1. Install root Electron dependencies
          npm install
          
          # 2. Install API dependencies
          cd utas_pax_demo_api
          npm install
          cd ..
          
          # 3. Build Flutter Web
          cd utas_pax_demo_flutter
          flutter pub get
          flutter build web --release --web-renderer canvaskit
          cd ..
          
          # 4. Package Electron EXE
          npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/*.exe # This grabs the portable EXE or installer
          if-no-files-found: error